name: Bug report
description: Create a report to help us improve
labels: bug
assignees: DanielRondonGarcia
body:
    - type: markdown
      attributes:
          value: |
              ¡Hola! Vemos que te gusta nuestro proyecto y has encontrado un error. Esto significa mucho para nosotros porque nos ayuda a mejorarlo aún más :)

    - type: textarea
      attributes:
          label: Describe el bug
          description: Escriba una descripción clara y concisa de cuál es el error.
          placeholder: |
              Ejemplo. Cuando trato de hacer esto, obtengo esto y debería ser esto...
      validations:
          required: true

    - type: textarea
      attributes:
          label: Pasos para reproducir
          description: Proporcione un enlace a un ejemplo en vivo o un conjunto inequívoco de pasos para reproducir este error. Incluir código para reproducir, si es relevante, eso significa mucho para nosotros.
          placeholder: |
              1.
              2.
              3.
              4.
      validations:
          required: true

    - type: textarea
      attributes:
          label: Comportamiento esperado
          description: Escriba una descripción clara y concisa de lo que esperaba que sucediera.
          placeholder: |
              Ejemplo. Debería conseguir esto...
      validations:
          required: true

    - type: textarea
      attributes:
          label: Capturas de pantalla, grabación de pantalla, fragmento de código
          description: |
              Si es posible, cargue una captura de pantalla o una grabación de pantalla que demuestre su error.
      validations:
          required: false

    - type: textarea
      attributes:
          label: Información del entorno
          description: |
               Incluya tantos detalles relevantes sobre el entorno en el que está trabajando.
          placeholder: |
            - PHP version
            - Development environment (MAMP, XAMPP, VVV, Docker, Laravel Valet, none if on live server)
            - Server type (Apache, Nginx, IIS)
            - Operating System and version
            - Libs version
            - Docker
      validations:
          required: false

    - type: dropdown
      id: existing
      attributes:
          label: Confirme que ha buscado problemas existentes en este repositorio.
          description: Puede hacer esto buscando https://github.com/actsis/actsis-docs/issues.
          multiple: false
          options:
             - 'Yes'
             - 'No'
      validations:
          required: true

    - type: dropdown
      id: docs
      attributes:
          label: Confirme que ha buscado en nuestra documentación y no ha podido encontrar la respuesta.
          description: Puede hacerlo buscando en https://www.actsis.com/.
          multiple: false
          options:
             - 'Yes'
             - 'No'
      validations:
          required: true
