name: Feature request
description: Sugiere una idea para este proyecto.
labels: feature request
assignees: DanielRondonGarcia
body:
    - type: markdown
      attributes:
          value: |
              ¡Hola! Vemos que te gusta nuestro proyecto y tienes algunas ideas. Esto significa mucho para nosotros porque nos ayuda a mejorarlo aún más :)
    - type: textarea
      attributes:
          label: Describa su solicitud de función
          description: Escriba una descripción clara y concisa de cuál es el problema.
          placeholder: |
              Ejemplo. Siempre me siento frustrado cuando...
      validations:
          required: true

    - type: textarea
      attributes:
          label: Describa la solución que le gustaría
          description: Por favor escribe una descripción clara y concisa de lo que quieres que suceda.
          placeholder: |
              Ejemplo. Con esta función podré...
      validations:
          required: true

    - type: textarea
      attributes:
          label: Capturas de pantalla, grabación de pantalla, fragmento de código
          description: |
              Si es posible, cargue una captura de pantalla o una grabación de pantalla que demuestre su solicitud de función.
      validations:
          required: false

    - type: dropdown
      id: existing
      attributes:
          label: Confirme que ha buscado problemas existentes en este repositorio.
          description: Puede hacer esto buscando https://github.com/actsis/actsis-docs/issues.
          multiple: false
          options:
             - 'Yes'
             - 'No'
      validations:
          required: true

    - type: dropdown
      id: docs
      attributes:
          label: Confirme que ha buscado en nuestra documentación y no ha podido encontrar la respuesta.
          description: Puede hacerlo buscando en https://www.actsis.com/.
          multiple: false
          options:
             - 'Yes'
             - 'No'
      validations:
          required: true