name: Algolia Scraping (Modo Desarrollo)

on:
  workflow_run:
    workflows: ["pages-build-deployment"]
    types:
      - completed
  workflow_dispatch:

jobs:
  algolia-scraping:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Instalar dependencias
        run: |
            cd website
            npm install
            npm install wait-on

      - name: Construir sitio en modo desarrollo
        run: |
            cd website
            npm run build:dev
        env:
          NODE_ENV: development

      - name: Iniciar servidor (background)
        run: |
          cd website
          nohup npm run start > server.log 2>&1 &
          echo "SERVER_PID=$!" >> $GITHUB_ENV

      - name: Verificar servidor listo
        run: |
          cd website
          npx wait-on http://localhost:3000 --timeout 120000
          echo "✅ Servidor listo en http://localhost:3000"

      - name: Ejecutar contenedor de scrapping
        env:
            APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
            API_KEY: ${{ secrets.API_KEY }}
        run: |
            docker run -e APPLICATION_ID=$APPLICATION_ID -e API_KEY=$API_KEY -e "CONFIG=$(cat ./website/config.dev.json | tr -d '\n')" algolia/docsearch-scraper

      - name: Detener servidor
        if: always()
        run: |
          kill -TERM ${{ env.SERVER_PID }} || true
